#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export OPENHOOK_DEPLOY_HOST="${OPENHOOK_DEPLOY_HOST:-openhook}"
export OPENHOOK_PUBLIC_URL="${OPENHOOK_PUBLIC_URL:-https://commute-planner.site}"
export OPENHOOK_REQUIRE_GITHUB="${OPENHOOK_REQUIRE_GITHUB:-1}"
export OPENHOOK_RUN_PRODUCTION_SMOKE="${OPENHOOK_RUN_PRODUCTION_SMOKE:-1}"
export OPENHOOK_WECOM_ROUTE_ID="${OPENHOOK_WECOM_ROUTE_ID:-rt_bnU7i41mLNCStFbYYsy4bg}"

log() {
  printf '[openhook production deploy] %s\n' "$*"
}

log "OPENHOOK_DEPLOY_HOST=${OPENHOOK_DEPLOY_HOST}"
log "OPENHOOK_PUBLIC_URL=${OPENHOOK_PUBLIC_URL}"
log "OPENHOOK_REQUIRE_GITHUB=${OPENHOOK_REQUIRE_GITHUB}"
log "OPENHOOK_RUN_PRODUCTION_SMOKE=${OPENHOOK_RUN_PRODUCTION_SMOKE}"
log "OPENHOOK_WECOM_ROUTE_ID=${OPENHOOK_WECOM_ROUTE_ID}"

"${ROOT_DIR}/scripts/deploy-openhook.sh"
